# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'QJDWB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QJDWB

pod 'SDWebImage'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'SnapKit'
pod 'MJRefresh'

end
